### ISSUE TITLE
VRaptor not working with Hibernate 4.1

### ISSUE THREAD

**Issue by adrianoalmeida7** [caelum/vraptor#432]
It throws a NoSuchMethodError at SessionCreator.create

Happened with Vraptor 3.4
